spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: shipment-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: apex-shipment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

apex:
  consumer:
    topic: apex.public.outbox_event
    event-type: ShipmentRequested
    dlt-topic: apex.shipment.events.DLT
  failure-injection:
    rate: ${SHIPMENT_FAILURE_RATE:0.0}
    trigger-account-ids: ${SHIPMENT_FAILURE_TRIGGER_ACCOUNT_IDS:}

server:
  port: 8082
