spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/apex
    username: apex
    password: apex
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081
